# playbooks/Neo4j_update.yml
---
- name: Update Neo4j config on this VM and restart (with safeguards + report)
  hosts: neo4j
  serial: 1
  any_errors_fatal: true
  gather_facts: false

  become: true
  become_user: "{{ neo4j_user | default('neo4j') }}"
  become_method: sudo

  vars_files:
    - "{{ playbook_dir }}/../inventories/vars.yml"  

  pre_tasks:
    - name: Precheck | Confirm neo4j.conf exists
      stat:
        path: "{{ neo4j_config_file }}"
      register: cfg

    - name: Precheck | Confirm neo4j CLI exists
      stat:
        path: "{{ neo4j_ctl }}"
      register: cli

    - name: Precheck | Fail early if files missing
      fail:
        msg: >-
          Missing required file(s):
          {% if not cfg.stat.exists %}neo4j.conf {% endif %}
          {% if not cli.stat.exists %}neo4j CLI{% endif %}.
          Check neo4j_home/neo4j_config_file/neo4j_ctl.
      when: not cfg.stat.exists or not cli.stat.exists

    - name: Precheck | Config is writable by run-as user
      command: test -w "{{ neo4j_config_file }}"
      register: writable_check
      changed_when: false

    - name: Precheck | Fail if config is not writable
      fail:
        msg: "neo4j.conf is not writable by {{ neo4j_user | default('neo4j') }}: {{ neo4j_config_file }}"
      when: writable_check.rc != 0

    - name: Capture status BEFORE
      command: "{{ neo4j_ctl }} status"
      register: status_before
      failed_when: false
      changed_when: false



      
  tasks:
    - name: Backup current config (timestamped)
      copy:
        src: "{{ neo4j_config_file }}"
        dest: "{{ neo4j_config_file }}{{ backup_suffix }}"
        remote_src: true

    - name: Ensure desired parameters are present/updated (idempotent)
      lineinfile:
        path: "{{ neo4j_config_file }}"
        regexp: '^(#\s*)?{{ item.key | regex_escape }}\s*=\s*.*$'
        line: "{{ item.key }}={{ item.value }}"
        backrefs: yes
      loop: "{{ config_parameters | dict2items }}"
      register: edit_results

    - name: Trigger restart if config changed OR force_restart=true
      when: (edit_results.results | selectattr('changed') | list | length) > 0
            or (force_restart | default(false) | bool)
      debug:
        msg: "Config changed or force_restart=true → restarting Neo4j"
      changed_when: true
      notify:
        - Restart via bin
        - Restart via service

    - meta: flush_handlers

    - name: Capture status AFTER
      command: "{{ neo4j_ctl }} status"
      register: status_after
      failed_when: false
      changed_when: false

    - name: Tail last logs (neo4j.log)
      command: "tail -n 80 {{ neo4j_home }}/logs/neo4j.log"
      register: tail_neo4j_log
      failed_when: false
      changed_when: false

    - name: Tail last logs (debug.log)
      command: "tail -n 80 {{ neo4j_home }}/logs/debug.log"
      register: tail_debug_log
      failed_when: false
      changed_when: false

    - name: Build run report | Set timestamp
      set_fact:
        run_ts: "{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
      changed_when: false

    - name: Build run report | Assemble content
      set_fact:
        run_report: |-
          Neo4j Ansible run on {{ inventory_hostname }} @ {{ run_ts }}
          run_as_user: {{ neo4j_user | default('neo4j') }}
          neo4j_home: {{ neo4j_home }}
          conf: {{ neo4j_config_file }}
          ctl: {{ neo4j_ctl }}
          wait target: {{ neo4j_wait_host }}:{{ neo4j_wait_port }}

          changed params: {{
            (edit_results.results | selectattr('changed') | map(attribute='item.key') | list) | join(', ')
            if edit_results is defined else 'n/a'
          }}

          ---- status BEFORE ----
          {{ status_before.stdout | default('') }}

          ---- status AFTER ----
          {{ status_after.stdout | default('') }}

          ---- tail neo4j.log ----
          {{ tail_neo4j_log.stdout | default('') }}

          ---- tail debug.log ----
          {{ tail_debug_log.stdout | default('') }}
      changed_when: false

  handlers:
    # --- BIN MODE ---
    - name: Stop Neo4j (bin)
      listen: "Restart via bin"
      when: not (neo4j_use_service | bool)
      command: "{{ neo4j_ctl }} stop"
      args:
        chdir: "{{ neo4j_bin_dir }}"

    - name: Start Neo4j (bin)
      listen: "Restart via bin"
      when: not (neo4j_use_service | bool)
      command: "{{ neo4j_ctl }} start"
      args:
        chdir: "{{ neo4j_bin_dir }}"

    - name: Wait for Bolt (bin)
      listen: "Restart via bin"
      when: not (neo4j_use_service | bool)
      wait_for:
        host: "{{ neo4j_wait_host }}"
        port: "{{ neo4j_wait_port }}"
        delay: 5
        timeout: 180

    # --- SERVICE MODE ---
    - name: Restart service
      listen: "Restart via service"
      when: (neo4j_use_service | bool)
      service:
        name: "{{ neo4j_service_name }}"
        state: restarted

    - name: Wait for Bolt (service)
      listen: "Restart via service"
      when: (neo4j_use_service | bool)
      wait_for:
        host: "{{ neo4j_wait_host }}"
        port: "{{ neo4j_wait_port }}"
        delay: 5
        timeout: 180
