---
- name: Start Neo4j only (bin mode)
  hosts: neo4j
  gather_facts: false

  become: "{{ neo4j_become }}"
  become_user: "{{ neo4j_become_user }}"
  become_flags: "-i"

  vars_files:
    - "{{ playbook_dir }}/../inventories/vars.yml"

  vars:
    neo4j_env:
      NEO4J_HOME: "{{ neo4j_home }}"
      NEO4J_CONF: "{{ neo4j_home }}/conf"
      PATH: "{{ neo4j_bin_dir }}:/usr/bin:/bin"
      JAVA_HOME: "{{ java_home }}"

  tasks:
    - name: Start Neo4j (bin) with ./neo4j start
      when: not (neo4j_use_service | bool)
      become: true
      become_user: neo4j
      become_flags: "-i"
      environment: "{{ neo4j_env }}"
      command: neo4j start
      args:
        chdir: "{{ neo4j_bin_dir }}"
