---
- name: Start Neo4j only (bin mode)
  hosts: neo4j
  gather_facts: false

  become: "{{ neo4j_become }}"
  become_user: "{{ neo4j_become_user }}"
  become_flags: "-i"

  vars_files:
    - "{{ playbook_dir }}/../inventories/vars.yml"

  vars:
    neo4j_env:
      NEO4J_HOME: "{{ neo4j_home }}"
      NEO4J_CONF: "{{ neo4j_home }}/conf"
      PATH: "{{ neo4j_bin_dir }}:/usr/bin:/bin"
      JAVA_HOME: "{{ java_home }}"

  tasks:
    - name: Start Neo4j (bin)
      when: not (neo4j_use_service | bool)
      become: true
      become_user: neo4j
      become_flags: "-i"
      environment: "{{ neo4j_env }}"
      shell: |
        set -euo pipefail
        echo "== EFFECTIVE USER =="; whoami; id
        echo "== CWD =="; pwd
        echo "== ENV (subset) =="; echo "JAVA_HOME=$JAVA_HOME"; echo "NEO4J_HOME=$NEO4J_HOME"; echo "PATH=$PATH"
        echo "== CMD =="; echo "{{ neo4j_ctl }} start (chdir={{ neo4j_bin_dir }})"
        cd "{{ neo4j_bin_dir }}"
        "{{ neo4j_ctl }}" start
      args:
        executable: /bin/bash
      register: start_trace
      changed_when: start_trace.rc == 0

    - name: Show start output
      when: not (neo4j_use_service | bool)
      debug:
        msg: |
          --- START rc={{ start_trace.rc | default('n/a') }} ---
          STDOUT:
          {{ start_trace.stdout | default('') }}
          STDERR:
          {{ start_trace.stderr | default('') }}
