---
- name: Start Neo4j (detached) and wait for readiness
  hosts: neo4j
  gather_facts: false

  become: "{{ neo4j_become }}"
  become_user: "{{ neo4j_become_user }}"

  vars_files:
    - "{{ playbook_dir }}/../inventories/vars.yml"

  vars:
    neo4j_env:
      NEO4J_HOME: "{{ neo4j_home }}"
      NEO4J_CONF: "{{ neo4j_home }}/conf"
      PATH: "{{ neo4j_bin_dir }}:/usr/bin:/bin"
      JAVA_HOME: "{{ java_home }}"

    bolt_host: "127.0.0.1"
    bolt_port: 7687
    bolt_timeout_sec: 300
    neo4j_log_tail_lines: 200

  tasks:
    - name: Who am I
      become: true
      command: whoami
      register: whoami_out

    - debug:
        msg: "Running as user: {{ whoami_out.stdout }}"

    - name: Check current Neo4j status (non-fatal)
      become: true
      become_user: "{{ neo4j_become_user | default('neo4j') }}"
      environment: "{{ neo4j_env }}"
      args:
        chdir: "{{ neo4j_bin_dir }}"
      command: ./neo4j status
      register: neo4j_status_before
      failed_when: false
      changed_when: false

    - name: Print current status
      debug:
        var: neo4j_status_before.stdout

    - name: Start Neo4j detached from SSH/session if not already running
