---
- name: Start Neo4j via systemd and wait for readiness
  hosts: neo4j
  gather_facts: false
  become: true

  vars_files:
    - "{{ playbook_dir }}/../inventories/vars.yml"

  vars:
    # Adjust if your unit is named differently (e.g., neo4j-community)
    neo4j_service_name: "neo4j"
    bolt_host: "127.0.0.1"
    bolt_port: 7687
    wait_timeout_sec: 300
    journal_lines: 200

  tasks:
    - name: Show effective user
      ansible.builtin.command: whoami
      register: whoami_out
    - ansible.builtin.debug:
        msg: "Running as: {{ whoami_out.stdout }}"

    - name: Ensure override directory exists
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ neo4j_service_name }}.service.d"
        state: directory
        mode: "0755"

    - name: Write systemd override (increase startup timeout, auto-restart)
      ansible.builtin.copy:
        dest: "/etc/systemd/system/{{ neo4j_service_name }}.service.d/override.conf"
        mode: "0644"
        content: |
          [Service]
          TimeoutStartSec=300s
          Restart=on-failure
          RestartSec=10s

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Neo4j
      ansible.builtin.systemd:
        name: "{{ neo4j_service_name }}"
        state: started
        enabled: true

    - name: Wait for Bolt port (Neo4j ready)
      ansible.builtin.wait_for:
        host: "{{ bolt_host }}"
        port: "{{ bolt_port }}"
        delay: 2
        timeout: "{{ wait_timeout_sec }}"

    - name: Show systemd status
      ansible.builtin.command: "systemctl --no-pager --full status {{ neo4j_service_name }}"
      register: neo4j_systemd_status
      changed_when: false
      failed_when: false
    - ansible.builtin.debug:
        var: neo4j_systemd_status.stdout

    - name: Tail recent Neo4j journal
      ansible.builtin.command: "journalctl -u {{ neo4j_service_name }} -n {{ journal_lines }} --no-pager"
      register: neo4j_journal
      changed_when: false
      failed_when: false
    - ansible.builtin.debug:
        var: neo4j_journal.stdout
