# .github/workflows/run-ansible.yml
name: Neo4j config update (dev)

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: [self-hosted]
    env:
      ANSIBLE_CONFIG: inventories/ansible.cfg
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info (debug)
        run: |
          echo "Runner: $(hostname)"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "JAVA_HOME from workflow: $JAVA_HOME"
          uname -a
          echo "Repo tree:"
          ls -R

      - name: Prepare SSH key
        run: |
          umask 077
          echo "${{ secrets.NEO4J_SSH_KEY }}" > "$GITHUB_WORKSPACE/id_rsa"
          chmod 600 "$GITHUB_WORKSPACE/id_rsa"

      - name: Ensure Ansible available (install if missing)
        run: |
          if ! command -v ansible >/dev/null 2>&1; then
            python3 -m pip install --user --upgrade pip
            python3 -m pip install --user ansible
            echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          fi
          ansible --version

      - name: Sanity checks
        run: |
          ansible
